### ISSUE TITLE
Discussion: Past Student Projects (UX and Research Directions)

### ISSUE THREAD

**Issue by ebeshero** [newtfire/digitProjectDesign-Hub#10]
Choose to explore and discuss one of the following project sites developed by students. Describe (in your own words):
*  at least one significant topic it seems to be exploring
* what research the developers might want to investigate next if the project were continuing
* the UX (user experience) of the project site, 
* what ideas it might inspire for new projects. 

[Divergences in Machine Translation (Harry Potter)](http://translate.obdurodon.org/)

[Banksy Project](https://banksy.newtfire.org/)

[The Hamilton Project](https://hamilton.newtfire.org)

[Eldritch Project](http://eldritch.newtfire.org/)

[Profanities in Quentin Tarantino's Screenplays](http://bamfs.obdurodon.org/index.xhtml)

[Twilight Princess (Zelda) Project](http://zelda.obdurodon.org/)

**Comment by JeremyF5737** [comment]
I chose the "Eldritch Project", which explores the topic of H.P Lovecraft's language and writing style in his famous works. The project deals with highlighting the compendium of obscure vocabulary that appears to trigger an emotional response from the reader. This is significant because H.P Lovecraft's writing is incredibly weird by todays standards like its trying to meet a work requirement for an English project that's due in five minutes. But as a reader, viewing these unknown describing terms can really confuse the reader and give a sense of mystery to the story as if the character is highly educated or can't put a basic description of what they are currently seeing.

If this project were to continue, it would be worth researching the amount of adjectives, nouns, and prepositions in the table of that of which the analysis was created on. Maybe even ranking the modernity of the all of the words they collected from commonly used today to almost never used in anything.

This project could inspire the same method for other works of literature, such as comparing _legally blonde_ to the play of _Hamilton_ , or the comparison of the _King James Bible_ to _Homers Iliad_. Another inspiration for a similar project would be to looking into the amount of time it took to write H.P Lovecraft's books and compare it to the amount of adjectives or the amount of obscure language that is written.

**Comment by ebeshero** [comment]
Make sure you turn on the sound when you visit Eldritch and some of the other sites!

**Comment by ebeshero** [comment]
This is a wonderfully thorough start for this review discussion. Thanks, @JeremyF5737 !

**Comment by dpakulski42** [comment]
I chose the Tarantino project. This project explores the usage of profanities and slurs in three of Tarantino's most popular screenplays and looks at the usage of these words in reference to male vs. female characters. It creates graphs that display these things as well as graphs depicting the parts of speech of each profanity and the most popular usage of each profanity.

If this project were to continue, I would suggest adding more of his screenplays. Tarantino has written and directed nine main features, three of which are included in this project. It would be particularly interesting to see what happens when a film like 'Kill Bill' or 'Jackie Brown' is added to the list. One of the main topics this project looks at is the usage of profanity and slurs by male vs. female characters to I would like to see what happens to the data when these female led films are added to the list.

This site was easy to move around and the info was displayed in a way that made sense. I'm not a huge fan of the colors and font. There could be some beautification that would make this site look a bit better.

This project could be good inspiration for another movie or script based project, which I would be really interested in. I thought they did a nice job with converting what they set out to do into a tangible project that you can learn something through.

**Comment by PiperBaron** [comment]
I chose the Banksy project. It provides a catalog listing out all of Banksy's work, timeline of when he did them, a map of locations that he tagged with his pieces, as well as some graphs showing a data analysis of his chosen locations and media. 

I would definitely suggest sorting his works by their themes, depictions, and/or keywords if the project were to continue. As it stands now, his art is only separated by type, as in "graffiti," "prints," etc. Banksy has many pieces that deal with similar subject matter or utilize the same kind of imagery (it's noted in the "About" section that he frequently uses rats in his work). I think as an artist primarily known for his satire, the main ideas of his pieces of the most important elements and should be easily searchable. 

The site is generally well-organized, but navigating it can be a bit awkward and perhaps even challenging for those with even slightly impaired eyesight. For example, when on the "Works" page, reading and clicking on each different section is a bit confusing due to the text reading top-to-bottom rather than left-to-right. Also, the text can be hard to read against some of the backgrounds, and would be a lot more readable if they were white outline with black (or if the backgrounds blended less with the red and black text they have now). The whole site could be better organized and designed aesthetically, but it's usable in its current state. 

I would love to see a project collecting graffiti and other types of street art on a wider scale, maybe focusing in on known groups like the [Yarn Bombers](https://streetartutopia.com/2011/07/13/yarn-bombing-guerrilla-crochet-a-collection/). Another project idea could be tracking the responses to graffiti/street art, like when street art is vandalized, covered up, or written/talked about in media. It's a contentious kind of art, so looking into how people interface with it might be worth researching.

**Comment by fammysillar** [comment]
I chose the Banksy project. It explores how the website works, the artist's works, and a map of where is works were produced. Along with,  the analysis, source, and the team that worked on this project. Overall I think everything offered to the viewers of the website was a good and complete way of showing off the artist and things he has done in an organized manner!
If the project was continuing, I would next recommend to maybe add additional photos in the map to actually see exactly what is being referenced. An example would be in Australia's semiperminant  festival ping. I thing it would be a good addition to add photos from that specific event!
I thought that the UX for this website was very easy flowing! The tabs were all easily accessible and had direct meanings. I also really liked the hover over feature in the works tab that lets you preview an image before you click on it!
This project can inspire other sited dedicated to lesser known artists by including them in things like the pictures I recommenced adding in the map tab!

**Comment by CodyCarlson17** [comment]
I chose the Harry Potter project. This project explores the Computational Methods in the Humanities and works with Linguistics. Since Harry Potter was originally in English, translation is very important. This website helps create translations and holds discussions for the better ways to reproduce the language in Harry Potter.

I think that if the project was to continue, they should focus in on the important events that happen in Harry Potter. That way, they will have the structure of the books complete and can just fill in the rest. They could possibly have descriptions or a key that helps explain certain spells and magic that occur in the books to help the reader understand more of what is going on in their language.

As the user, I feel that it is a very useful idea and the way they approached the project was well intended, but there is little translation done. I would suggest to these people working on this project to look into a language converter of some sort. If you can code/program a script that allows the user to say something into a device that the program can translate it into the language it is needed for. That is a lot of coding and work, but it can be done if this is what they truly are going for.

This project may inspire others to do something similar for just about anything. There is a lot of music, books, tv shows, etc that people don't watch because they don't understand the language in them. If there was a way to translate them that would be very useful and this form of entertainment would see an increase in views/purchases.

**Comment by MasonG27** [comment]
I took a look into the zelda project! It grabbed my attention right away because I am a huge fan of the zelda series and their projection is awesome! What I got from the projects goals and ideas was they wanted to find a way to organize and catagorize the cultures of hyrule, the world of the zelda series. As they say it is indeed very diverse and dynamic as you move throughout the game which seems to make this tast tough but the way they broke it up into acts and chapters as well as characters and their details was the best way they could have went about it. 
My favorite iteration by far was the graphs that they built. Showing the graphs to present the differences in each act as well as chapter was a great way to show the diversity throughout the game, and almost gives you a timeline type of feeling. The inclusion of the full script was a also a very nice touch for the people  that want to look into the greatest details of the project! My last positive comment is that creating an index and a bio for each character im sure took a while but really brought the project all together, for people like me that love to find out detailed information about tons of different characters. My only critique would be that for the chapters section in the graphs, it gets a little messy and conjoined. I would have liked to see the acts maybe presented underneath the chapters, in a grouping fashion. Other than that, this was a great project and I would love to see them do this on another game in the series, like breath of the wild!

**Comment by zteyssier** [comment]
I decided to investigate the Profanities in Quentin Tarantino's Screenplays project.  This project analyzes the use of swear words and slang words among Pulp Fiction, Django Unchained, and Inglorious Bastards.  I thought it was interesting that the developers graphed the parts of speech for the curse words.  

The developers may want to consider adding more or all of Tarantino's films into the project.  The team could consider overlapping actors such as Samuel Jackson in Pulp Fiction and Hateful Eight.  They could compare his profanity between the two different characters.  

The user experience is smooth with working links across the menu.  The site could possibly use fewer colors for its color scheme.  The text is readable in front of the grey background.  The graphs are simple with analysis afterward to explain the results.  

A project could made with Christopher Nolan Films.  Instead of exploring profanities, the project could explore themes across Inception, Tenet, and Momento.  The characters could be compared, along with dialogue, and personality.  Hanz Zimmer's soundtrack from Inception and The Dark Knight could be compared to find similar motifs, instrumentation, and scales.

**Comment by AreannaRussell** [comment]
For this assignment I chose the “Twilight Princess (Zelda) Project”. This project focuses on different types of languages based on race, gender, and linguistic patterns. Based on the conclusion they said that they might add another category of separating speech by Hometown as well as adding a hover over function to the speaker graphs. I like their interface to appoint. Like characters, conclusion, and about are well organized and easy for the user to navigate through but I do think that they could’ve also linked the names of characters in full script page to the characters page. But other than that the pages info doesn’t take up too much space but gives enough to understand the project. This project could inspire our new projects for the new Zelda “breath of the wild“game, any kind of game that deals with talking characters, plays, or movies/TV shows as they all deal with speech to add to story/plot/atmosphere.

**Comment by beealex** [comment]
I chose the "Divergences in Machine Translation (Harry Potter) not only because it sounded interesting, but also because it is my favorite movie series of all time. The project explores the linguistics of the Harry Potter series based on book releases from multiple areas of the world. The project developers focused on the translations from certain German, French and Slovak language to English to see how the meaning of the text changed. After reading through the various tabs, I feel as though the developers could have been more descriptive with their project purpose as well as personal information. While personal info may not be as important, they could’ve explained their individual reason for the project OR they could have explained how it connected to their major. As a user, it would be more helpful to have the site menu/tabs at the top of the page rather than underneath photos. This would result in easier navigation and it would also make the site slightly more appealing. It is also harder to read due to the font choice, mainly when reading headings. On the other hand, I like that there is a background image to spice up the page. Furthermore, I enjoy that the image is frozen in the back while the text flows. Because of this set up, it is easier to focus on the text itself since there are larger paragraphs to read. After taking a look at this project, I think it would be cool to analyze similar linguistic scenarios with other books or plays. It might even be interesting to analyze an Elizabethan play since the language is fairly different. It could then be compared to modern language structures.

**Comment by CTrohoske01** [comment]
I decided to explore the Bansky project. The site explores a variety of aspects regarding Bansky ranging from who his is, his projects, a map of where all of his projects are located, a brief timeline, etc. I think the timeline is very intriguing and the most interesting to me.

If they were to continue I think it would be good to just keep updating information. I don't know what else they could add in terms of content regarding Bansky, but they could add some pizzazz. When it comes to the analysis they could add a zoom feature on the visualizations to make it a bit easier to read. Even tho you can click on it and open the image and then zoom it would just be more efficient!

This could inspire a variety of art projects in the future. I'm sure there are many out there already, but this could be a part of a comprehensive cataloging project including many artists. It could become a huge art project that gets many people involved in the art community!

**Comment by Joelpie** [comment]
For this dicsussion I chose to look at the "Twilight Princess (Zelda) Project". This project includes a comprehensive collection of dialogue found in the Nintendo-published game of the same name. The purpose of this project is to determine how characters talk, and how their characteristics influence the speech they use. Categories include the full script of the game, a list of characters, and graphs which illustrate the collected data of the project (though some are left empty).

It'd be nice to have a map (if there is one) to connect some characters together. Each character's hometown is listed under their bios, so it'd be nice to see how these locations could somehow influence the way they speak.

In terms of UX, I'd suggest changing the font and putting the menu bar at the top of the page, the Times New Roman look is a rather bland one. Everything is responsive though, and navigation is an easy task.

The reason I chose to look at this project is because I recognized the title as a video game, and wanted to see what types of projects video games could influence. This has inspired me to make my own project regarding video games, but what that will be, I don't yet know.

**Comment by ebeshero** [comment]
@Joelpie and others interested in Zelda and maybe a game project: I have seen a number of good projects involving game analysis. Here is one you might find interesting that involved working with a game map to organize the game data they were marking up: http://bloodborne.newtfire.org/

Try clicking on the Map of Yharnam tab, and click any of the text names on the map. The team experimented with image mapping a couple of different ways to get that working!
