### ISSUE TITLE
Project Proposal: Disney Songs Continuation 

### ISSUE THREAD

**Issue by amayadwillis** [newtfire/digitProjectDesign-Hub#42]
My project proposal is to pick back up on the Disney songs project Jackie and I started last semester in DIGIT 210. We both love Disney movies and we greatly enjoyed comparing and analyzing all of the songs from the Aladdin franchise last year. To build upon this project we would like to start incorporating more movie franchises onto the site and change the layout a little to better fit having multiple franchises (as of right now it is only built for one). 

As a refresh or for those who are unfamiliar these are the questions we looked at: Do the songs (original and reprised versions) contain the same or similar words? What parts of speech do these songs contain the most, and what does the variation in words mean? How much did the songs reflect the overall theme of the movie/franchise?

We would likely continue to work with DisneyClips (https://www.disneyclips.com/lyrics/) for our lyrics. You can check out our existing website and GitHub at these links:

https://amayadwillis.github.io/DisneySongs/index.html
https://github.com/amayadwillis/DisneySongs

**Comment by wdjacca** [comment]
On the same page as Amaya, I would also like to extend our scope for the Disney Songs project. As for the movie franchises, I think we can extend to Beauty and the Beast, or Little Mermaid since there are many remakes and spin-offs of the same franchise. Another source that we can also take lyrics from is [All The Lyrics]([](https://www.allthelyrics.com/lyrics/disney) ) as well as [Disney Song Lyrics](http://www.fpx.de/fp/Disney/Lyrics/). 

For the site layout, I think we can include more graphics and interactive elements, as well as incorporate more networking graphs.

We can expand the research topic to include the ratio of each character's part in the songs, as well as the spread out of them in the duration of the movies.

**Comment by BarbieCessar** [comment]
I am a big Disney fan so this project stood out to me. I think analyzing Disney songs would be interesting to see how similar/ different they are from each other. This is a really cool project idea and I could see myself joining this project.

**Comment by Emily-Levi** [comment]
I love Disney movies and songs. I think it would be interesting to see what other Disney movie songs you would incorporate into this project. How many more songs/movies would you be adding to this project? This is also a project I would consider joining.

**Comment by Kennaab** [comment]
This project proposal seems very fun to create and add to the existing project. I have always been a big movie bug and some of the people in my life have been too. 

I think it would be interesting to add Pixar movies.

https://disney.fandom.com/wiki/Category:Pixar_songs

I think this website has a lot of useful information for Pixar movies/songs with the lyrics written out.

**Comment by wdjacca** [comment]
@Kennaab I certainly would also love to add Pixar movies! During the initial project, we considered the Toy Story franchise since it is a big and popular franchise, but there weren't too many songs so we ultimately went with Aladdin.
