### ISSUE TITLE
Project Proposal: Willy Wonka/Charlie and the chocolate factory comparison

### ISSUE THREAD

**Issue by Emily-Levi** [newtfire/digitProjectDesign-Hub#45]
My Project proposal is to compare and analyze the movies Willy Wonka and the chocolate factory and Charlie and the chocolate factory. I want this project to focus on the similarities and differences between these movies, including character comparisons, character songs and the overall storyline of the movie. 

scripts 
https://its-always-veggie-bone-lebowski-party-knuckles.fandom.com/wiki/Charlie_and_the_Chocolate_Factory_script
https://wonkadotcom.tripod.com/script.html

**Comment by amayadwillis** [comment]
I think it would be interesting to see the outcome of that comparison and what you can come up with to figure out how to display your findings. Did you have an accessible resource you can use to get the scripts of those movies? If so you should link them on this issue so potential groupmates can check them out!

**Comment by san5281** [comment]
Maybe because I grew up watching a lot of 70s movies but I am very curious to see how this project will work. I think this project would work well not only as a comparison between the two movies but also as a comparison between the shift as what defined a family movie back in the 70s vs the more modern version. Comparing the directors and their former works may also help with this and would be very cool in my opinion!

**Comment by bwm5473** [comment]
Interesting. I think sans5281 has some good points too. If you are going to incorporate the style of each movie into your project, maybe you could also consider learning about the tone and pacing of each movie, maybe even the accuracy of each movie to the original source material.

**Comment by Scarlett-Lion** [comment]
it would be nice to contrast as well. the way Charlie got a ticket was different in both movies , and although both Wonka and Charlie rood the elevator in both movies, they only visited Wonka dad in the newer version. even some on the trouble that the kids get into is different, Both movies where a art of my child hood and I cant wait to see how this turns out. i would recommend rewatching/watching the movies before starting anything.
