### ISSUE TITLE
Project Proposal: Kingdom Hearts/Secondary Proposal

### ISSUE THREAD

**Issue by austinmurry** [newtfire/digitProjectDesign-Hub#46]
For my first proposal, my thoughts were to continue and refine my project from DIGIT 210. We did a project based around the Kingdom Hearts franchise and we had a lot of great work, we looked at characters and how many times a specific character spoke vs other characters and saw which characters interacted with whom and how often they interacted with the same characters across the 3 main titles, but a lot of things could have been more organized. If I was to take a look at this project again, I would want to dive deeper into what we looked at previously but also look into maybe locations that are frequented across the multiple titles and maybe look into the deeper story of the 3 main titles and see what portions of them are similar to each other and where they start to branch off. I would want to update the website to look and feel smoother and more fluid, create better graphs and overall just organize our code to be more user friendly. Scripts for the three titles can be found on the GitHub Pages website we created last year as well as all of our information on our GitHub repo. Links:

Repository: https://github.com/Beeplosion/KingdomHeartOfTheCards
Website: https://beeplosion.github.io/KingdomHeartOfTheCards/

My second proposal idea is to look into the game Destiny 2. This is a game that has a story to it, but some of the deeper lore of the story is found through lore books that the player can find by doing certain objectives in game. I would like to take a look at these lore books and break them apart. I want to take a look at who the speaker is, whom they are speaking to, what the topic is about and from there make a timeline of events based on the in-game story and the story from the lore books to the current point in the game. From there I want to also take a look at just how many times each character has their own lore tab and then possibly even look into the patterns of whom the speakers are talking to and the frequency. We can also the take a look at maps of the game and pin point actual locations of where each lore book takes place. The transcripts for each of the lore books can be found in the link below.

Lore Book Transcripts: https://www.ishtar-collective.net/transcripts

**Comment by san5281** [comment]
I'd be interested in Kingdom Hearts as I am very interested in taking a look at the series again and exploring the potential deeper themes within it!

**Comment by Cameron-Bigi** [comment]
I would love to help to expand on the old Kingdom Hearts project. I a huge fan of the franchise, I've been play them ever since kingdom hearts 1 on the ps2. I would be very interested in what you've made so far for it, because I know that the franchise is very long and very confusing in a lot of areas. But I've already done some deep research into the games myself and would love to contribute any of my knowledge.

**Comment by wdjacca** [comment]
I would love to help with the Kingdom Hearts project since it's like combining my love for Disney and gaming together! I love the idea of comparing the storylines together, and I think that would give some interesting data. I think an interactive map would serve well to display the interactions within the storylines and the characters in the game!

**Comment by JesseBeckwith1998** [comment]
I worked on this project last semester and would like to continue to build on it as there was so much more we weren't able to get to due to time constraints.  I would like to update the website to make it flow better and format it so that it looks less clunky.
