### ISSUE TITLE
project proposal: Dragon Age lore 

### ISSUE THREAD

**Issue by Scarlett-Lion** [newtfire/digitProjectDesign-Hub#48]
I am a fan of the dragon age saga and I remembered that last year I heard someone did the lore for an elders schools game by using the codex entries, so I thought it would be a good idea to use the codex entrees from the dragon age game or just one to compile and sort a list for that. i thought for the data we could find a complete codex list from and online source.

**Comment by ebeshero** [comment]
For reference, the Elder Scrolls project from last fall is here: http://morrowind.newtfire.org/

**Comment by Scarlett-Lion** [comment]
here is a list of the codex entries in dragon age inquisition 
https://dragonage.fandom.com/wiki/Category:Dragon_Age:_Inquisition_codex_entries

**Comment by JesseBeckwith1998** [comment]
Dragon age is one of those games I never got into, mostly because of elder scrolls, however, it would be pleasant to work with another game series that differs from that of the Kingdom Hearts project I worked on last semester. Possibly making charts of the different types of enemies, the number of bosses per game, repetition of characters and lines from said characters, etc. there is lots to do with this project idea!
