### ISSUE TITLE
Project Proposal: Super Smash Bros 

### ISSUE THREAD

**Issue by BarbieCessar** [newtfire/digitProjectDesign-Hub#54]
This project would revolve around the game Super Smash Bros. I'm a big fan and I've been playing this game since it was on the Nintendo 64. I'm sure there are other fans as well. This project would analyze the different versions of the game and how it has evolved over the years. Most of all I want to analyze all of the characters on Super Smash. Each version gets new characters and I want to see how they are all different/similar to each other. We could even look into the tiers of characters. I'm very open to suggestions. I think there is a lot we can do and I would be very eager to make a project about Super Smash Bros.

**Comment by trumerfe** [comment]
Hey Barbie! I'm a super big Smash fan too, I'd be super down to work on this since I know a lot about the series and I'm interested in it too!

**Comment by austinmurry** [comment]
I really like this idea as well Barbie! I am a huge fan of the Super Smash games as well and I have grown up playing them too since the Nintendo 64. I think it would be cool to make some sort of a timeline of when the games released and you can even go as far as to add the consoles to that line up as well. Then for new characters, some were added to thee games over time (more with Smash Ultimate now with the fighter passes), but it would be cool to make an interactive timeline that has the characters released as well. A graph can be made of the characters that appear across all of the titles so you can check for consistency there as well. Overall I would love to be apart of this project if my project isn't as widely liked and accepted!

**Comment by trumerfe** [comment]
I think including a section that reviews character buffs/nerfs throughout the games would be interesting too, as there were balancing changes even between games for a lot of characters. Also, showing notable competitive players for each character could add do the project.

**Comment by am0eba-byte** [comment]
This sounds like such a fun project idea Barbie! I love Super Smash Bros, and there are so many intricacies to the game and all of the different versions that have come out over the years that there's a plethora of opportunity for cool data research and visualizations to be done to highlight the awesomeness of the game. I think it would be cool to develop a timeline of the different platforms SSB has been released on over the years, the elements of the game that have been improved as time has progressed, and the characters that have been added. This is a project I could see myself working on for sure.

**Comment by Emily-Levi** [comment]
This sounds like a really interesting Project Proposal Barbie. I think adding a section about special moves would be an interesting addition. I am very interested in the possibility of joining this project.

**Comment by AtomicOlsen** [comment]
Nothing wrong with smash that's for sure, I could see myself doing this project, I enjoy the variety in information we could categorize, especially with the expansive ultimate roster.

**Comment by ebeshero** [comment]
@BarbieCessar or others here: An issue: How do you deal with the game franchise and its own resources? What would your project do differently than what is already available on the Nintendo site: https://www.smashbros.com/en_AU/fighter/index.html  ?

**Comment by Scarlett-Lion** [comment]
if your are doing smash bros I would recommend talking about the different mini games and trophies you can get in the different game. for example in the 3ds version you could customize your characters with different upgrades, and even make a mii a fighter.

**Comment by Cameron-Bigi** [comment]
Its a good idea, I also really enjoy smash brothers. I've been playing that ever since it first came out. I know that you would want to analyze all of the characters of the game but how would you handle the characters like the miis where the player can completely change the way they are played and look. And also there are characters that are physically different selections but have the exact same move set. Would they both get a entre or would they be combined somehow.

**Comment by amw6765** [comment]
Think this would be quite a fascinating project idea, especially for the game fanatics! There is a lot of different ways you could go with this project in terms of comparisons. I think you have the right idea in wanting to compare and contrast the different characters from game to game. Since there happens to be a number of recreations of this game you will have a good opportunity to collect your data. You could maybe even compare and contrast the design of the characters/maps in each of the games
