### ISSUE TITLE
Project Proposal: League of Legends world

### ISSUE THREAD

**Issue by Beeplosion** [newtfire/digitProjectDesign-Hub#55]
I was thinking with how varied the characters are in League of Legends, maybe one good project idea could be of showing a kind of map base on their relations, and where they are from within the world.

**Comment by san5281** [comment]
League of Legends is one of the most popular video games in the world (I believe it was during its peak) so archiving its different stages would be extremely useful from a historical standpoint especially since it started out from a much smaller company. Since you seem to be not completely decided, talking about its history (including the differences in the lore as the game became more popular) would be nice!

**Comment by wdjacca** [comment]
I think it is interesting to note the relations between the LoL champions, and would be able to give background knowledge of the game to avid and new players. One suggestion for the project scope is to include the references of what the champions are based off on and maybe where in the real world would they be based (WuKong from China and Chinese mythology, Anubis from Egypt and Egyptian mythology etc)

**Comment by sxa585** [comment]
I am not super big into LOL, I probably have like 20 hours into the game. But I think something that would be SUPER interesting to look into is the sort of esports aspect of LOL being the biggest one in the world it might be super cool to look into what its like in the international competition do some sort of stat analysis or the different aspects in cultures of the different regions in things like media coverage.
