### ISSUE TITLE
Project Proposal: NASA & SpaceX Spacecraft Launches

### ISSUE THREAD

**Issue by amw6765** [newtfire/digitProjectDesign-Hub#61]
For this project I think it would be quite interesting to create a timeline & synopsis for the spacecraft launches (either: only manned launches / both manned and automated launches). The timeline would consist of launches from both NASA and SpaceX. I think it be fun to be able to see the different spacecrafts used throughout the years and the crew aboard them (if present). As well as, where and how these spacecrafts has succeeded or failed throughout the years.

**Here are some links:** 
https://www.spacex.com/launches/

https://www.nasa.gov/missions

https://www.nasa.gov/mission_pages/station/expeditions/past.html

https://www.britannica.com/list/7-accidents-and-disasters-in-spaceflight-history

**Comment by austinmurry** [comment]
I like this idea a lot Anthony! I am a huge space fan and was very intrigued by this proposal. I like your idea of looking into the SpaceX missions and NASA missions, as they are two of the larger corporations. The timeline idea is great and I think to have everything in a nice and concise space would be awesome. You could also see if there is a way to make an interactive timeline that can be clicked on and show all of the launches of that year and possibly a picture of the mission itself. I think you should incorporate the unmanned missions into this as well since they are still missions. It would be cool to see the upgrade of spacecrafts over time and what different technology was used from early on to now. Overall I love this project idea and am excited to see how it turns out.

**Comment by am0eba-byte** [comment]
This sounds like it could turn into a SUPER nifty project. I think it'll be interesting to document and see the data differences between government-funded space missions (NASA) and Musky Boi's missions. I'd also be cool to see comparisons in how much money was spent on manned vs. unmanned missions, and develop a personography of all the people who've gone to space. This is a unique project idea compared to all the others! There are so many possibilities. Definitely on my top 3 list of projects I'd love to be a part of.

**Comment by ebeshero** [comment]
@amw6765 One of the last project teams I worked with at my old Pitt-Greensburg post in Spring 2020 did a project a little more limited than this one on Rocket Launches. You could possibly start with their code base and improve on it for this one? Here's the project: 
Website: http://rocket.newtfire.org/index.html
GitHub: https://github.com/robftg/Rocket-Launches

**Comment by amw6765** [comment]
Awesome!! I appreciate the extra resources. Thank you Dr. B ☺️

**Comment by N00000DLE** [comment]
This project seems really cool. When we were looking at the one launch document in class, I thought it was fascinating, so seeing this as an idea piqued my interest. It could also be cool to possibly visualize the path that these ships took, not sure if that is possible, but that way you can visualize when people r saying what. I think that this project has a huge area that it can grow too and has a lot of potential.
