### ISSUE TITLE
UX Discussion 

### ISSUE THREAD

**Issue by ebeshero** [newtfire/digitProjectDesign-Hub#7]
Choose one of the following digital archives to explore and write a post in this thread discussing its "UX" or "User Experience". More than one of you will choose the same site, so respond to each other if you want to expand on or reply to each other:
1)  What the site is inviting us to explore: what can you learn from this site, and what do you find interesting here?
2) What do you think of the site's organization? How easily do you navigate it to find information?
3) When you interact with the site's interface (clicking, opening, looking at pages) what stands out as working well, and what might not be working so well?

Sites to explore (choose one to discuss in your posting):
* [Map of Early Modern London](https://mapoflondon.uvic.ca/index.htm)
* [Emily Dickinson Project](https://dickinson.newtfire.org/) (prepared by Pitt-Greensburg students)
* [What's on the Menu?](http://menus.nypl.org/) (Be sure to read the About page for the project's goals)
* [My Immortal](http://imm.dh.obdurodon.org/) (prepared by Pitt-Oakland students)
* [LOTR Project](http://lotrproject.com/)

**Comment by zteyssier** [comment]
1. I chose the My Immortal project.  I can understand the intentions and the idea of a troll though the "lens" of the author, Tara Gillespie.  I find it interesting that there is a whole index for the author's use of language.  This helps unpack the meaning behind the words or phrases. 
 
2. The information is presented in a logical and neat format.  The color scheme could be less diverse.  The site could appeal more to people with colorblindness by only using a small friendly-range of colors.  The site is accessible and the pages are informative for the user.  

3. For the most part, the site's interface is very responsive and informative per topic.  The Grammar Mistakes By Sentence graph under the Statistics section, does not seem to be in working order.  The graph varies in size per chapter, but the plot points for specific grammar mistakes do not update accordingly.

**Comment by dpakulski42** [comment]
1. I choose the Lord of the Rings project. The site is attempting to lay out a timeline of Tolkien's books by creating things like maps and family trees. I really like seeing everything laid out in the way it is on this site. It's really interesting to see the scale of which these stories take place.
2. I think the site is organized fairly well. The pages are neatly placed in the top left corner and everything is easy to navigate. I suppose the only difficulty is with the expanse of knowledge and detail that Tolkien provides, the info can seem a little overwhelming for someone who doesn't know the stories very well.
3. I was able to jump between pages well but I found moving around within that page was a little difficult. Things like clinking and dragging around the family tree and zooming in and out of the map felt a little choppy.

**Comment by beealex** [comment]
1. I chose to explore the LOTR project and it was amazing! The publishers of the site did a great job incorporating canon characters/events vs non-canon characters/events. Overall, they allowed the user to really dive deep into Tolkien's work on the Lord of the Rings series, even if the user was unfamiliar before. Even if the user was unfamiliar with Tolkien’s well-known series, the publishers included a family tree with descriptions and relationships between each character. This was very fascinating to read through! It definitely took a lot of time and I respect how in-depth and captivating they made it.
2. I found the site very easy to navigate as the name of the web pages were simply labeled, but very descriptive. When scanning through the family tree and the map, it was very well organized and easy to navigate since it was plainly laid out. Overall the site’s organization was incredible! There were so many different web pages that had a ton of information—you clicked on one page and another draws you in.
3. It’s interesting how, when you go to the menus in the upper left-hand corner, the text that you hover over highlights red. However, when you hover over the social media links, the boxes light up according to the traditional colors/shades of each social media’s theme. Alongside text lighting up, I enjoy that they make the headings a specific color to not only match the theme of their website, but it is easier on the eyes for users to navigate. The loading time (which obviously can vary by the computer as well) is fairly short which allows for quicker retrieval of information. The map surprisingly enough didn’t take that long to load, however, the family tree takes a little longer to develop on the page. The one thing I did notice was that when you click on the merchandise found in the “Store” it doesn’t open a new URL which makes it a little difficult to compare items side by side. There is also a language barrier when clicking on the merchandise which is just because of the type/location of the store on the web.

**Comment by CTrohoske01** [comment]
1. I decided to check out The Lord of The Rings project. It has a variety of things ranging from maps, to character genealogy, to just simple blog posts about the topic. The maps are super interesting, done with detail, and fun. It's always cool to see fictional stories become so visualized and interactive, even if it's just a simple map on your computer.
2. I think it's organized fairly well. All the topics are organized at the top of the screen and the home page is pretty straight-forward. The timelines section is organized well, easy to scroll through and to select on the map which makes making the connection easy. The statistics pages is organized in well defined sections that make it easy to digest the information. Also on the statistics page, I love how the section/section options stay with the user as you continue to scroll down the page. Kind of hard to describe, but if you go there you will know what I am talking about.
3. Every time I would return to the homepage the family tree would take a really long time to load and would display a loading symbol and message for around 20 seconds. No big deal to me, but maybe something that can be improved upon. Another thing was when you selected a map and displayed the paths, the area around the path when you hovered over it to recognize it was very small, so you have to be very precise with where your cursor is. Maybe just expanding the area where the path is recognized, just a little bit, would make it feel less frustrating. At least to me.

**Comment by PiperBaron** [comment]
1. I also chose the My Immortal project, and I had so much reading through it. I was vaguely familiar with it before (as the whole thing is a long-running meme), but I learned a lot about fan culture and the whole concept of “trolling” through fan fiction, which is an inherently hilarious idea on its own. Trolling is a pastime as old as the Internet itself, but I’d never seen it happen in a medium like this before, and I found it strangely creative.

2. The site is well-organized and nicely designed; navigating to the different sections and finding what you’re looking for is pretty intuitive. The aesthetics are a bit much, but I think they’re rather fitting for the subject matter. I really appreciated the addition of the codex, so you can read through every reference to popular culture made without sifting through and Googling everything yourself.

3. Most of the site functions well, but I noticed a few minor issues when going through each section. For example, the alignment of the information box on specific pages of the Codex is really off and bleeds from the main part of the site onto the background.

**Comment by JeremyF5737** [comment]
1.	I chose the “What’s on the menu?” project. The website wants it’s users to explore the evolution of the historical restaurants menus from the 1850’s to 2008 to see how the food choices evolved from the ages. From this project you can see how the restaurants menu has evolved from very blunt descriptions such as “cold meats” and “fish” without any descriptions besides the name to specific entrees such as “Grilled Brook Trout” with a description of the sides and what you are receiving. I find the fact that you could eat a pigs tongue from 1850 on the menu, while by todays standards that would be unacceptable.
2.	The site’s organization for the main tabs is simple, you can look at the restaurants menus from a time period, you can look up a specific dish by using a search bar or filter options, data export logs, and a blog for the developers to recite their edits. The site makes it easy to explore the menu’s from different time periods, there are over 460,000 recipes in the recipe tab so if you wanted to show someone a specific dish/entrée from the 1920’s you would have multiple restaurants so you would have to rely on the specific name or restaurant it came from.
3.	The website makes finding a random menu from a time period which is organized from years In 10 year increments such as 1870’s, 1930’s, and 2000’s. Where the website falls short is when looking for an archived recipe such as a “New York style steak” will show multiple restaurant menu’s that have the same item and all of their recipes, where I was just looking for a specific recipe It just organizes the menu items from the closest time period menu to the last results in the past that contained that item. TLDR- its too difficult to look up a broad item from a restaurant you did not keep track of.

**Comment by fammysillar** [comment]
1. I chose "What's on the Menu" project.This project contains over 45,000 menus from the New York Public Library's rare book division. Reading through this, I was really interested. This isn't a site I would normally click on, but I am glad I got to see how it is set up and organized. 
2. Although the search is broken(ish? the homepage said it was but it kind of worked for me),  I like how everything is split between Menu and recipe categories, and then within them you have the option to pick by year. I do also really enjoy the amount of pictures and how they move when scrolled over.
3. The search has to be pretty specific, and then from there you have to go through menus so if you dont have the specifics of something it will probably be a little difficult to find things instantly.

**Comment by Joelpie** [comment]
For this discussion, I chose to look at the LOTR project.

1. This site contains maps of Middle Earth the entire genealogy of the Lord of the Rings series. It's presented as multiple trees, some much larger than others, with lines connecting family members in a hierarchy. It's interesting to see such a large cast of characters localized visually on just one website. Now I'm just thinking about how other series' genealogies would stack up in comparison of size. Game of Thrones would certainly be a neat one to see.

2. The organization of the sight is pretty good, but the immense size of the visuals have an unpleasant effect on the browsing experience. The website performs slowly when scrolling from one side to another. If a more compact design was possible, it probably should have been implemented.

3. The site is very detailed. Every character has a readable blurb at the click of a name, and are color coated based on whether or not they're from the books, a game, or from some other outside media. Again, the only thing that takes away from the experience is the initial navigation of the genealogy, which is only due to the scope of the project.

**Comment by elmusfi** [comment]
I chose the What’s on the Menu? project, which hosts a collection of transcribed menus from the restaurant menu collection in the New York Public Library. You can look at 17,000 different menus from the 1850's to today, and I find it really interesting that you can also look up individual dishes, of which there are over 400,000 of them.

The site’s organization is pretty good, it has a tab for the menus and another one for the dishes, as well as a data and blog tab. You can look at the menus and dishes by decade, popularity (dishes), dish count (menus), name, and their completion status (done, new, under review). I’d also like it if they could be able to sort it by the type of cuisine, or even the ingredients used (so if someone’s allergic they can avoid their allergen). Sure it doesn’t have recipes or anything, but it’d be nice to see where someone could have gotten food or what they could have eaten in, say, the 1870's if they couldn’t eat peaches (Kiarsarge House in 1873 happened to have peach fritters).

Something I’d do different when clicking on dishes is if there’s only 1 menu it’s present on, clicking on the name of the dish should go straight to that menu, not to the page for the dish because the dish page shows the low/high price, and the years it’s appeared on a menu, which it’s kind of useless when there’s only one price point and year it appears. Maybe write some code to bypass that page if it’s gonna be the only item to show? I also think that the menu page should have the enlarged images showing already to flip through, with the index present in a side bar so someone can see the restaurant info while looking through the menu pictures. There’s not really a need for the tiny picture previews in the index, just replace that with a gallery to look through all menu images at a legible size.

**Comment by CodyCarlson17** [comment]
I chose The Map of Early Modern London. On this website, you can find out information about the layout of the city in early modern London. You can see where a specific building or place is according to the map. There is also a library, encyclopedia, and about the website tab. These have citations and other information about where all of the map has come from. 

I think that the site is very organized and it is easy to go through. All of the information is under its designated tab and is very organized. The design of the website is clean looking. It is easily readable and there are no issues with fonts. The site has an encyclopedia option if you don't understand what something is.

Everything looks well coded and managed when clicking around on the site. The only thing that I could see that could be done to help improve the experience for the user is creating an interactive map. It would be cool if you could click on a specific location and you as the user would receive quick metadata about that spot on the map. Other than that, I thought the site was extremely well made.

**Comment by AreannaRussell** [comment]
For this UX discussion I chose the my Immortal project as it is something I’m familiar with and I found to be hilarious.  
What we learn through this project is how many misspellings where in the fan fiction, Mark up methods that were used to cater specifically towards this fan fiction such as references, sex, and kiss. The interesting stuff I found about this project is how every new page gives you a new phrase from the story,a photo of how that character would look from the story, and what chapter it was in. 
Overall I found the organization end navigation of the site to be easy and simple while also being full of information like why, about, the fanfic itself. The interface kind of reflects the theme of the story which was early 2000’s Gothic. I don’t know if the simple layout was inspired by the early 2000’s web layout (old YouTube layout) or if it was just easier to do it this way but that also adds to the theme. 
The interface also had a bunch of links  for more information and if you hover over blue words they explain why they are blue like a misspelling of black. what I don’t really like about the interface is that it's on the left side of the screen (on my computer) then the center screen and the chapter font is kind of small. I feel they had room to make it bigger in both font and page.

**Comment by MasonG27** [comment]
1. On the lord of the rings archive project there are tons of different ways to gather information. There is an extravagant family tree system as well as links to information for almost all the characters involved in the series. There is the indication of several details on the surface as well of each character, such as their race and their persona/house type (god, elder, noldor, etc) which I thought was a very nice touch before clicking on the link to give a full bio. 

2. I found that there was a ton of navigation to do on this project. I think it could have been presented a little better, possibly in a more condensed fashion although I understand how it would be difficult to do as there are so many different layers of family trees. The best way to improve would be to have as much navigation as possible on one part of the screen instead of having to scroll and then have those navigators have subsets that open up into other navigations which would be the family trees. 

3. The interaction is great, I thought it worked as intended, all the links that I used worked and were presented in a nice and straightforward way. The only thing I questioned was the permalink button just takes you back to the beginning, which might be intended, I just thought it was a bit strange to incorporate that.
